sudo: required
before_install:
  - sudo apt-get install make
  - sudo apt-get install g++
  - sudo apt-get install git
  
# Enable C++ support
language: cc

# Compiler selection
compiler:
  - gcc
  
install:
  - sudo git clone https://github.com/libtom/libtommath
  - cd libtommath
  - sudo make install
  - cd ..
  - sudo git clone https://github.com/libtom/libtomcrypt
  - cd libtomcrypt
  - make CFLAGS="-DUSE_LTM -DLTM_DESC" EXTRALIBS="-ltommath" install
  - cd ..
  - cd TS3Client

# Build steps
script:
  - sudo make -f make main
